# Generated by Django 4.1.7 on 2023-03-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRegistration', '0003_userextended_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='advisor',
            field=models.BooleanField(default=False),
        ),
    ]
