# Generated by Django 4.1.7 on 2023-04-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseRegistration', '0005_coursetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextended',
            name='takenCourses',
        ),
    ]
