# Generated by Django 4.1.7 on 2023-04-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseRegistration', '0006_remove_userextended_takencourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.CharField(default='TR', max_length=3),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='CS', max_length=4),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
