# Generated by Django 4.0.1 on 2023-04-23 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseRegistration', '0007_remove_course_description_course_course_course_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetaken',
            name='course',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coursetaken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
