# Generated by Django 4.0.1 on 2023-04-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseRegistration', '0008_alter_coursetaken_course_alter_coursetaken_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.RemoveField(
            model_name='realschedule',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='user',
        ),
        migrations.DeleteModel(
            name='DraftSchedule',
        ),
        migrations.DeleteModel(
            name='RealSchedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
