# Generated by Django 4.1.7 on 2023-03-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminderDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
