# Generated by Django 4.1.7 on 2023-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_alter_task_enddate_alter_task_reminderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminderDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
